In [3]:
import kaggle

In [32]:
!kaggle datasets download anshika2301/vrinda-store-data-analysis -f "Store Data.xlsx"
path = !kaggle datasets download anshika2301/vrinda-store-data-analysis -f "Store Data.xlsx"
# import kagglehub

# Download latest version
# path = kagglehub.dataset_download("anshika2301/vrinda-store-data-analysis")

print("Path to dataset files:", path)

Dataset URL: https://www.kaggle.com/datasets/anshika2301/vrinda-store-data-analysis
License(s): CC0-1.0
Downloading Store%20Data.xlsx.zip to E:\Excel Files\Excel Project\Vrinda Store Data Analysis

  0%|          | 0.00/3.60M [00:00<?, ?B/s]
 28%|##7       | 1.00M/3.60M [00:01<00:04, 648kB/s]
 56%|#####5    | 2.00M/3.60M [00:01<00:01, 1.22MB/s]
 83%|########3 | 3.00M/3.60M [00:02<00:00, 2.01MB/s]
100%|##########| 3.60M/3.60M [00:02<00:00, 2.33MB/s]
100%|##########| 3.60M/3.60M [00:02<00:00, 1.69MB/s]

NameError: name 'path' is not defined

In [33]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('Store%20Data.xlsx.zip')
zip_ref.extractall()
zip_ref.close()

In [2]:
#read data from the file and handle null values
import pandas as pd
# df = pd.read_excel('Store Data.xlsx')
df = pd.read_excel('Vrinda Store Data Analysis.xlsx')
df.head(20)

,index,Order ID,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
5,6,407-1298130-0368305,1298130,Men,49,2022-12-04,Delivered,Flipkart,JNE3797-KR-XXL,Western Dress,XXL,1,INR,735,SANGLI MIRAJ KUPWAD,MAHARASHTRA,416436,IN,False
6,7,407-1298130-0368305,1298130,Women,23,2022-12-04,Delivered,Meesho,JNE3801-KR-XXL,kurta,XXL,1,INR,735,BENGALURU,KARNATAKA,560029,IN,False
7,8,171-5561216-3398711,5561216,Women,70,2022-12-04,Delivered,Others,JNE3405-KR-M,kurta,M,1,INR,435,GURUGRAM,HARYANA,122001,IN,False
8,9,408-2935263-2935550,2935263,Women,75,2022-12-04,Delivered,Amazon,JNE3474-KR-E-XL,kurta,XL,1,INR,385,BENGALURU,KARNATAKA,562149,IN,False
9,10,404-2648970-9042715,2648970,Women,43,2022-12-04,Delivered,Myntra,JNE3466-KR-L,kurta,L,1,INR,771,VIJAYAWADA,ANDHRA PRADESH,520002,IN,False
10,11,404-2648970-9042715,2648970,Women,76,2022-12-04,Delivered,Amazon,JNE3795-KR-S,kurta,S,1,INR,517,THIRUVANANTHAPURAM,KERALA,695018,IN,False
11,12,404-2648970-9042715,2648970,Women,45,2022-12-04,Delivered,Myntra,J0181-TP-M,Top,M,1,INR,399,ARAKONAM,TAMIL NADU,631003,IN,False
12,13,408-0265357-4939534,265357,Women,18,2022-12-04,Delivered,Amazon,SET217-KR-PP-XL,Set,XL,1,INR,786,GUWAHATI,ASSAM,781017,IN,False
13,14,403-9268874-7296313,9268874,Men,44,2022-12-04,Delivered,Myntra,SET185-KR-NP-M,Set,M,1,INR,911,BENGALURU,KARNATAKA,562125,IN,False
14,15,407-0442660-2736366,442660,Women,52,2022-12-04,Delivered,Amazon,SET333-KR-DPT-M,Set,M,1,INR,967,HYDERABAD,TELANGANA,500098,IN,False
15,16,406-7482261-1657136,7482261,Women,18,2022-12-04,Delivered,Nalli,J0124-TP-L,Top,L,1,INR,523,NEW DELHI,DELHI,110062,IN,False
16,17,407-7039962-7080347,7039962,Men,30,2022-12-04,Delivered,Meesho,SET304-KR-DPT-XL,Set,XL,1,INR,1115,Bhubaneswar,ODISHA,751022,IN,False
17,18,407-3422488-7373923,3422488,Women,48,2022-12-04,Delivered,Others,SET184-KR-PP-XS,Set,XS,1,INR,563,SIROHI,RAJASTHAN,307001,IN,False
18,19,171-8974687-6745940,8974687,Men,24,2022-12-04,Delivered,Myntra,J0161-DR-XXL,Western Dress,XXL,1,INR,473,MUMBAI,MAHARASHTRA,400097,IN,False
19,20,406-0244536-2177175,244536,Women,46,2022-12-04,Delivered,Amazon,SET233-KR-PP-M,Set,M,1,INR,545,AMRITSAR,PUNJAB,143001,IN,False

In [3]:
# Shape (Rows, Columns)
# print("Shape:", df.shape)

# Data types aur null values
print(df.info())

# Pehli 5 rows
# df.head()

<class 'pandas.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             31047 non-null  int64
 1   Order ID          31047 non-null  str
 2   Cust ID           31047 non-null  int64
 3   Gender            31047 non-null  str
 4   Age               31047 non-null  int64
 5   Date              31047 non-null  datetime64[us]
 6   Status            31047 non-null  str
 7   Channel           31047 non-null  str
 8   SKU               31047 non-null  str
 9   Category          31047 non-null  str
 10  Size              31047 non-null  str
 11  Qty               31047 non-null  int64
 12  currency          31047 non-null  str
 13  Amount            31047 non-null  int64
 14  ship-city         31047 non-null  str
 15  ship-state        31047 non-null  str
 16  ship-postal-code  31047 non-null  int64
 17  ship-country      31047 non-null  str
 18  B2B               31047 non-null  bool
dtypes: bool(1), datetime64[us](1), int64(6), str(11)
memory usage: 4.3 MB
None

In [4]:
# Check karo kahan-kahan null hai
print(df.isnull().sum())

index               0
Order ID            0
Cust ID             0
Gender              0
Age                 0
Date                0
Status              0
Channel             0
SKU                 0
Category            0
Size                0
Qty                 0
currency            0
Amount              0
ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
B2B                 0
dtype: int64

In [5]:
# Check duplicates
print("Duplicates:", df.duplicated().sum())

# Agar hain toh drop karo
 df = df.drop_duplicates()

Duplicates: 0

In [78]:
df

,index,Order ID,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,4724097,Men,60,2022-01-06,Delivered,Flipkart,J0083-KR-XL,kurta,XL,1,INR,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,4724097,Men,34,2022-01-06,Delivered,Myntra,J0010-LCD-S,Set,S,1,INR,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,3572295,Men,29,2022-01-06,Delivered,Amazon,SET398-KR-PP-L,Set,L,1,INR,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1423498,Men,46,2022-01-06,Delivered,Amazon,JNE3568-KR-M,kurta,M,1,INR,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,4694875,Men,36,2022-01-06,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,1,INR,791,WARANGAL,TELANGANA,506001,IN,False

In [8]:
# Modify Columns
# df.columns = df.columns.str.replace('-', '_')
df = df.rename(columns={'Channel_': 'Channel'})
df.columns

Index(['index', 'Order_ID', 'Cust_ID', 'Gender', 'Age', 'Date', 'Status',
       'Channel', 'SKU', 'Category', 'Size', 'Qty', 'currency', 'Amount',
       'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'B2B'],
      dtype='str')

In [9]:
# df.columns
df.info

<bound method DataFrame.info of        index             Order_ID  Cust_ID Gender  Age       Date     Status  \
0          1  171-1029312-3038738  1029312  Women   44 2022-12-04  Delivered
1          2  405-2183842-2225946  2183842  Women   29 2022-12-04  Delivered
2          3  171-1641533-8921966  1641533  Women   67 2022-12-04  Delivered
3          4  404-7490807-6300351  7490807  Women   20 2022-12-04  Delivered
4          5  403-9293516-4577154  9293516  Women   62 2022-12-04  Delivered
...      ...                  ...      ...    ...  ...        ...        ...
31042  31043  405-4724097-1016369  4724097    Men   60 2022-01-06  Delivered
31043  31044  405-4724097-1016369  4724097    Men   34 2022-01-06  Delivered
31044  31045  408-3572295-5992330  3572295    Men   29 2022-01-06  Delivered
31045  31046  405-1423498-9705162  1423498    Men   46 2022-01-06  Delivered
31046  31047  408-4694875-8249153  4694875    Men   36 2022-01-06  Delivered

        Channel                      SKU       Category Size  Qty currency  \
0        Myntra  JNE1233-BLUE-KR-031-XXL          kurta  XXL    1      INR
1          Ajio           SET414-KR-NP-L            Set    L    1      INR
2        Myntra           SET261-KR-PP-S            Set    S    1      INR
3        Amazon           SET110-KR-PP-M            Set    M    1      INR
4        Myntra         JNE2294-KR-A-XXL          kurta  XXL    1      INR
...         ...                      ...            ...  ...  ...      ...
31042  Flipkart              J0083-KR-XL          kurta   XL    1      INR
31043    Myntra              J0010-LCD-S            Set    S    1      INR
31044    Amazon           SET398-KR-PP-L            Set    L    1      INR
31045    Amazon             JNE3568-KR-M          kurta    M    1      INR
31046  Flipkart            J0341-DR-XXXL  Western Dress  3XL    1      INR

       Amount    ship_city   ship_state  ship_postal_code ship_country    B2B
0         376       MOHALI       PUNJAB            140301           IN  False
1        1449     GURUGRAM      HARYANA            122002           IN  False
2         453      KOLKATA  WEST BENGAL            700029           IN  False
3         729    THANJAVUR   TAMIL NADU            613007           IN  False
4         544     GURUGRAM      HARYANA            122001           IN  False
...       ...          ...          ...               ...          ...    ...
31042     565         PUNE  MAHARASHTRA            412307           IN  False
31043     939    BENGALURU    KARNATAKA            560061           IN  False
31044    1115  PITHORAGARH  UTTARAKHAND            262501           IN  False
31045     399        DHULE  MAHARASHTRA            424006           IN  False
31046     791     WARANGAL    TELANGANA            506001           IN  False

[31047 rows x 19 columns]>

In [81]:
df

,index,Order_ID,Cust_ID,Gender,Age,Date,Status,Channel_,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,4724097,Men,60,2022-01-06,Delivered,Flipkart,J0083-KR-XL,kurta,XL,1,INR,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,4724097,Men,34,2022-01-06,Delivered,Myntra,J0010-LCD-S,Set,S,1,INR,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,3572295,Men,29,2022-01-06,Delivered,Amazon,SET398-KR-PP-L,Set,L,1,INR,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1423498,Men,46,2022-01-06,Delivered,Amazon,JNE3568-KR-M,kurta,M,1,INR,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,4694875,Men,36,2022-01-06,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,1,INR,791,WARANGAL,TELANGANA,506001,IN,False

In [82]:
df.info
df.head()

,index,Order_ID,Cust_ID,Gender,Age,Date,Status,Channel_,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False

In [18]:
# df.head(5)
print(df.info())
# df.columns = df.columns.str.lower()

<class 'pandas.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_index       31047 non-null  int64
 1   order_id          31047 non-null  str
 2   cust_id           31047 non-null  int64
 3   gender            31047 non-null  str
 4   age               31047 non-null  int64
 5   date              31047 non-null  datetime64[us]
 6   status            31047 non-null  str
 7   channel           31047 non-null  str
 8   sku               31047 non-null  str
 9   category          31047 non-null  str
 10  size              31047 non-null  str
 11  qty               31047 non-null  int64
 12  currency          31047 non-null  str
 13  amount            31047 non-null  int64
 14  ship_city         31047 non-null  str
 15  ship_state        31047 non-null  str
 16  ship_postal_code  31047 non-null  int64
 17  ship_country      31047 non-null  str
 18  b2b               31047 non-null  bool
dtypes: bool(1), datetime64[us](1), int64(6), str(11)
memory usage: 4.3 MB
None

In [23]:
# Column rename karo
# df = df.rename(columns={'index': 'Order_index'})
df.dtypes
# df.head(5)

order_index                  int64
order_id                       str
cust_id                      int64
gender                         str
age                          int64
date                datetime64[us]
status                         str
channel                        str
sku                            str
category                       str
size                           str
qty                          int64
currency                       str
amount                       int64
ship_city                      str
ship_state                     str
ship_postal_code             int64
ship_country                   str
b2b                           bool
dtype: object

In [26]:
df

,order_index,order_id,cust_id,gender,age,date,status,channel,sku,category,size,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,4724097,Men,60,2022-01-06,Delivered,Flipkart,J0083-KR-XL,kurta,XL,1,INR,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,4724097,Men,34,2022-01-06,Delivered,Myntra,J0010-LCD-S,Set,S,1,INR,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,3572295,Men,29,2022-01-06,Delivered,Amazon,SET398-KR-PP-L,Set,L,1,INR,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1423498,Men,46,2022-01-06,Delivered,Amazon,JNE3568-KR-M,kurta,M,1,INR,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,4694875,Men,36,2022-01-06,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,1,INR,791,WARANGAL,TELANGANA,506001,IN,False

In [29]:
# 'index=False' lagana zaroori hai warna Pandas apna row number bhi save kar dega
# df.to_csv('cleaned_vrinda_store_data.csv', index=False)
# print("File saved successfully!")


df.to_excel('cleaned_vrinda_store_data.xlsx', index=False)
print("Excel file saved successfully!")

Excel file saved successfully!

In [28]:
#load the data into sql server using replace option
import sqlalchemy as sal
# engine = sal.create_engine('mssql://MUZER\MSSQLSERVER01/OnlineBookStore?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
# engine = sal.create_engine('mssql+pyodbc://sa:Abc%40123@MUZER%5CMSSQLSERVER01/OnlineBookStore?driver=ODBC+Driver+17+for+SQL+Server')
engine = sal.create_engine(
    "mssql+pyodbc://sa:Abc%40123@MUZER\\MSSQLSERVER01/OnlineBookStore?driver=ODBC+Driver+17+for+SQL+Server"
)
conn=engine.connect()

In [22]:
#load the data into sql server using append option
df.to_sql('Stores', con=conn , index=False, if_exists = 'append')

27